# Generated by Django 5.1.4 on 2025-03-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verify_sid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Verify SID'),
        ),
    ]
