# Generated by Django 5.1.4 on 2025-04-19 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_country_city_currency'),
        ('users', '0003_user_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_users', to='common.country'),
        ),
    ]
