# Generated by Django 5.1.4 on 2025-03-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('formal_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Formal Name')),
                ('iso2', models.CharField(blank=True, max_length=15, null=True, verbose_name='iso2')),
                ('iso3', models.CharField(blank=True, max_length=15, null=True, verbose_name='iso3')),
                ('dial_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Dial Code')),
                ('emoji', models.CharField(blank=True, max_length=15, null=True, verbose_name='Emoji')),
                ('flag', models.CharField(blank=True, max_length=150, null=True, verbose_name='Flag')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
