# Generated by Django 5.1.4 on 2025-04-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='country',
            field=models.ManyToManyField(blank=True, related_name='country_currencies', to='data.country'),
        ),
    ]
