# Generated by Django 5.1.4 on 2025-04-17 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_currency_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='country',
            new_name='countries',
        ),
    ]
