# Generated by Django 5.1.4 on 2025-04-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_rename_country_currency_countries'),
        ('partners', '0017_alter_partner_billing_city_and_more'),
        ('users', '0004_alter_user_phone_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='countries',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
