# Generated by Django 5.1.4 on 2025-03-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importprocess',
            name='progress',
            field=models.PositiveIntegerField(default=0, verbose_name='Progress'),
        ),
        migrations.AddField(
            model_name='importprocess',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done')], default='pending', max_length=25, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='importprocess',
            name='task_id',
            field=models.CharField(default=0, max_length=250, unique=True, verbose_name='Task ID'),
            preserve_default=False,
        ),
    ]
