# Generated by Django 5.1.4 on 2025-03-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_importprocess_progress_importprocess_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importprocess',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=25, null=True, verbose_name='Status'),
        ),
    ]
