# Generated by Django 5.1.4 on 2025-04-03 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_importprocess_status'),
        ('companies', '0003_alter_invitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='importprocess',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='import_processes', to='companies.company'),
            preserve_default=False,
        ),
    ]
