# Generated by Django 5.1.4 on 2025-04-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_importprocess_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='importprocess',
            name='items_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Items Count'),
        ),
    ]
