# Generated by Django 5.1.4 on 2025-04-19 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_importprocess_items_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('formal_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Formal Name')),
                ('iso2', models.CharField(blank=True, max_length=15, null=True, verbose_name='iso2')),
                ('iso3', models.CharField(blank=True, max_length=15, null=True, verbose_name='iso3')),
                ('dial_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Dial Code')),
                ('emoji', models.CharField(blank=True, max_length=15, null=True, verbose_name='Emoji')),
                ('flag', models.CharField(blank=True, max_length=150, null=True, verbose_name='Flag')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='City')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_cities', to='common.country')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('symbol', models.CharField(blank=True, max_length=25, null=True, verbose_name='Symbol')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Exchange Rate')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('countries', models.ManyToManyField(blank=True, related_name='country_currencies', to='common.country')),
            ],
        ),
    ]
