# Generated by Django 5.1.4 on 2025-04-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_country_city_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='City'),
        ),
    ]
