# Generated by Django 5.1.4 on 2025-03-11 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Partner Name')),
                ('formal_name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Partner Formal Name')),
                ('image', models.ImageField(blank=True, help_text='Please upload a square image, otherwise center will be cropped.', null=True, upload_to='media/docs/companies/ ', verbose_name='Image')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='companies.company')),
            ],
        ),
    ]
