# Generated by Django 5.1.4 on 2025-03-16 22:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
