# Generated by Django 5.1.4 on 2025-04-01 20:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_partner_created_date_partner_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
