# Generated by Django 5.1.4 on 2025-04-04 14:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_partner_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], max_length=25, verbose_name='Status'), blank=True, default=list, null=True, size=None),
        ),
    ]
