# Generated by Django 5.1.4 on 2025-04-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_partner_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='formal_name',
            field=models.CharField(max_length=140, verbose_name='Partner Formal Name'),
        ),
    ]
