# Generated by Django 5.1.4 on 2025-04-08 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('partners', '0006_alter_partner_formal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_partners', to='data.country'),
        ),
    ]
