# Generated by Django 5.1.4 on 2025-04-08 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_city'),
        ('partners', '0007_partner_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_partners', to='data.city'),
        ),
    ]
