# Generated by Django 5.1.4 on 2025-04-15 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_city'),
        ('partners', '0009_partner_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='phone_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_country_partners', to='data.country'),
        ),
        migrations.AddField(
            model_name='partner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone Number'),
        ),
    ]
