# Generated by Django 5.1.4 on 2025-04-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0010_partner_phone_country_partner_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='address2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Address 2'),
        ),
    ]
