# Generated by Django 5.1.4 on 2025-04-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0012_partner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='vat_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vat No'),
        ),
        migrations.AddField(
            model_name='partner',
            name='vat_office',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vat Office'),
        ),
    ]
