# Generated by Django 5.1.4 on 2025-04-17 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_city'),
        ('partners', '0013_partner_vat_no_partner_vat_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='billing_address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Billing Address'),
        ),
        migrations.AddField(
            model_name='partner',
            name='billing_address2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Billing Address 2'),
        ),
        migrations.AddField(
            model_name='partner',
            name='billing_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_city_partners', to='data.city'),
        ),
        migrations.AddField(
            model_name='partner',
            name='billing_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_country_partners', to='data.country'),
        ),
    ]
