# Generated by Django 5.1.4 on 2025-04-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0014_partner_billing_address_partner_billing_address2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_billing_same',
            field=models.BooleanField(default=False),
        ),
    ]
