# Generated by Django 5.1.4 on 2025-04-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0015_partner_is_billing_same'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='partner',
            name='web',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Web'),
        ),
    ]
