# Generated by Django 5.1.4 on 2025-04-19 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_country_city_currency'),
        ('partners', '0016_partner_about_partner_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='billing_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_city_partners', to='common.city'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='billing_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_country_partners', to='common.country'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_partners', to='common.city'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_partners', to='common.country'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phone_country_partners', to='common.country'),
        ),
    ]
