# Generated by Django 5.1.4 on 2025-01-30 21:58

import companies.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Company Name')),
                ('formalName', models.CharField(blank=True, max_length=140, null=True, verbose_name='Company Formal Name')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.SET(companies.models.get_sentinel_user), related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
