# Generated by Django 5.1.4 on 2025-05-11 13:25

import companies.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_city_name'),
        ('companies', '0004_company_uuid_usercompany_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='display_currency',
            field=models.ForeignKey(default=companies.models.get_default_currency, on_delete=django.db.models.deletion.CASCADE, related_name='currency_user_companies', to='common.currency'),
        ),
    ]
