# Generated by Django 5.1.4 on 2025-02-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_rename_formalname_company_formal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
