# Generated by Django 5.1.4 on 2025-03-11 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='subscription', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(blank=True, choices=[('free', 'Free'), ('standart', 'Standart'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=25, null=True, verbose_name='Type')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='Duration')),
                ('startDate', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Start Date')),
                ('endDate', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
            ],
        ),
    ]
