# Generated by Django 5.1.4 on 2025-01-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
    ]
