# Generated by Django 5.1.4 on 2025-04-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_account_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Balance'),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('receivable', 'Receivable'), ('payable', 'Payable')], default='receivable', max_length=10, verbose_name='Type'),
        ),
    ]
