# Generated by Django 5.1.4 on 2025-04-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_account_balance'),
        ('common', '0007_country_city_currency'),
        ('companies', '0003_alter_invitation_status'),
        ('partners', '0017_alter_partner_billing_city_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('partner', 'currency'), name='unique_partner_currency'),
        ),
    ]
