# Generated by Django 5.1.4 on 2025-04-26 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_transaction'),
        ('companies', '0003_alter_invitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='companies.company'),
            preserve_default=False,
        ),
    ]
