# Generated by Django 5.1.4 on 2025-04-29 12:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_transaction_company'),
        ('common', '0007_country_city_currency'),
        ('companies', '0004_company_uuid_usercompany_uuid'),
        ('partners', '0017_alter_partner_billing_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_accounts', to='common.currency'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('invoice_no', models.CharField(blank=True, max_length=140, null=True, verbose_name='Invoice No')),
                ('type', models.CharField(choices=[('sale', 'Sales Invoice'), ('purchase', 'Purchase Invoice')], default='sale', max_length=10, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Amount')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='companies.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_invoices', to='common.currency')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_invoices', to='partners.partner')),
            ],
        ),
    ]
