# Generated by Django 5.1.4 on 2025-04-30 17:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_transaction_ref_uuid'),
        ('common', '0008_alter_city_name'),
        ('companies', '0004_company_uuid_usercompany_uuid'),
        ('partners', '0017_alter_partner_billing_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('payment_no', models.CharField(blank=True, max_length=140, null=True, verbose_name='Payment No')),
                ('type', models.CharField(choices=[('incoming', 'Incoming Payment'), ('outgoing', 'Outgoing Payment')], default='incoming', max_length=10, verbose_name='Type')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Amount')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='companies.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_payments', to='common.currency')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_payments', to='partners.partner')),
            ],
        ),
    ]
