# Generated by Django 5.1.4 on 2025-04-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('receivable', 'Receivable'), ('payable', 'Payable'), ('bank', 'Bank')], default='receivable', max_length=10, verbose_name='Type'),
        ),
    ]
