# Generated by Django 5.1.4 on 2025-05-08 20:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_alter_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='accounting.accountcategory')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_type_accounts', to='accounting.accounttype'),
        ),
    ]
