# Generated by Django 5.1.4 on 2025-05-08 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_accountcategory_accounttype_alter_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountcategory',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='accountcategory',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='updated_date',
        ),
    ]
