# Generated by Django 5.1.4 on 2025-05-10 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_remove_accountcategory_created_date_and_more'),
        ('partners', '0019_alter_partner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_accounts', to='partners.partner'),
        ),
    ]
