# Generated by Django 5.1.4 on 2025-05-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_alter_account_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ref_uuid',
            field=models.CharField(max_length=140, verbose_name='Ref UUID'),
        ),
    ]
