# Generated by Django 5.1.4 on 2025-03-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('navigation', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, help_text='Please upload a square image, otherwise center will be cropped.', null=True, upload_to='media/docs/notifications/ ', verbose_name='Image')),
                ('is_read', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
