name: Marswide Backend CI/CD

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8000:8000
          - 5433:5432

    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
    
    - name: Create .env file
      run: |
        cat <<EOF > .env
        ${{ secrets.ENV_FILE }}
        EOF
    
    - name: Build and Push Docker image
      run: |
        docker network create marswide_network
        docker-compose down --remove-orphans
        docker-compose -f docker-compose.prod.yml up --build -d
    
    - name: Create DB user and database if not exists
      run: |
        docker-compose exec db bash -c "
          psql -U postgres -tc \"SELECT 1 FROM pg_roles WHERE rolname='mars';\" | grep -q 1 || psql -U postgres -c \"CREATE USER mars WITH PASSWORD '9527';\";
          psql -U postgres -tc \"SELECT 1 FROM pg_database WHERE datname='marswide';\" | grep -q 1 || psql -U postgres -c \"CREATE DATABASE marswidedb OWNER mars;\";
        "

    - name: Django settings and test
      env:
        DJANGO_SETTINGS_MODULE: core.settings
        DATABASE_URL: postgres://postgres:mars@db:5432/marswidedb_test
      run: |
        docker-compose exec web python manage.py migrate

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Connect to server with SSH and deploy it
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/admin/marswide/marswide_backend
          git pull origin master
          docker-compose down --remove-orphans && docker-compose -f docker-compose.prod.yml up --build -d
          docker-compose exec web python manage.py migrate
